
include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Icon
BUNDLE_EXTENSION = .viewer

$(BUNDLE_NAME)_OBJC_FILES = $(wildcard *.m)
$(BUNDLE_NAME)_STANDARD_INSTALL = no
$(BUNDLE_NAME)_PRINCIPAL_CLASS = IconViewer

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
