usr/share/WindowMaker/autostart.sh
usr/share/WindowMaker/exitscript.sh
usr/share/locale/it/LC_MESSAGES/WPrefs.mo
usr/share/locale/it/LC_MESSAGES/WindowMaker.mo
usr/share/locale/da/LC_MESSAGES/WindowMaker.mo
usr/share/locale/de/LC_MESSAGES/WPrefs.mo
usr/share/locale/de/LC_MESSAGES/WindowMaker.mo
usr/share/locale/de/LC_MESSAGES/wmgenmenu.mo
usr/share/locale/de/LC_MESSAGES/WINGs.mo
usr/share/locale/ro/LC_MESSAGES/WindowMaker.mo
usr/share/locale/hy/LC_MESSAGES/WindowMaker.mo
usr/share/locale/bg/LC_MESSAGES/WPrefs.mo
usr/share/locale/bg/LC_MESSAGES/WindowMaker.mo
usr/share/locale/bg/LC_MESSAGES/WINGs.mo
usr/share/locale/nl/LC_MESSAGES/WindowMaker.mo
usr/share/locale/ja/LC_MESSAGES/WPrefs.mo
usr/share/locale/ja/LC_MESSAGES/WindowMaker.mo
usr/share/locale/pt/LC_MESSAGES/WPrefs.mo
usr/share/locale/pt/LC_MESSAGES/WindowMaker.mo
usr/share/locale/ru/LC_MESSAGES/WPrefs.mo
usr/share/locale/ru/LC_MESSAGES/WindowMaker.mo
usr/share/locale/no/LC_MESSAGES/WindowMaker.mo
usr/share/locale/zh_CN/LC_MESSAGES/WPrefs.mo
usr/share/locale/zh_CN/LC_MESSAGES/WindowMaker.mo
usr/share/locale/be/LC_MESSAGES/WindowMaker.mo
usr/share/locale/sk/LC_MESSAGES/WPrefs.mo
usr/share/locale/sk/LC_MESSAGES/WindowMaker.mo
usr/share/locale/sk/LC_MESSAGES/WINGs.mo
usr/share/locale/ko/LC_MESSAGES/WPrefs.mo
usr/share/locale/ko/LC_MESSAGES/WindowMaker.mo
usr/share/locale/cs/LC_MESSAGES/WPrefs.mo
usr/share/locale/cs/LC_MESSAGES/WindowMaker.mo
usr/share/locale/cs/LC_MESSAGES/WINGs.mo
usr/share/locale/hr/LC_MESSAGES/WPrefs.mo
usr/share/locale/hr/LC_MESSAGES/WindowMaker.mo
usr/share/locale/gl/LC_MESSAGES/WindowMaker.mo
usr/share/locale/hu/LC_MESSAGES/WPrefs.mo
usr/share/locale/hu/LC_MESSAGES/WindowMaker.mo
usr/share/locale/fr/LC_MESSAGES/WPrefs.mo
usr/share/locale/fr/LC_MESSAGES/WindowMaker.mo
usr/share/locale/fr/LC_MESSAGES/wmgenmenu.mo
usr/share/locale/fr/LC_MESSAGES/WINGs.mo
usr/share/locale/sv/LC_MESSAGES/WindowMaker.mo
usr/share/locale/el/LC_MESSAGES/WindowMaker.mo
usr/share/locale/fi/LC_MESSAGES/WPrefs.mo
usr/share/locale/fi/LC_MESSAGES/WindowMaker.mo
usr/share/locale/zh_TW/LC_MESSAGES/WPrefs.mo
usr/share/locale/zh_TW/LC_MESSAGES/WindowMaker.mo
usr/share/locale/tr/LC_MESSAGES/WindowMaker.mo
usr/share/locale/es/LC_MESSAGES/WPrefs.mo
usr/share/locale/es/LC_MESSAGES/WindowMaker.mo
usr/share/locale/es/LC_MESSAGES/wmgenmenu.mo
usr/share/locale/ca/LC_MESSAGES/WPrefs.mo
usr/share/locale/ca/LC_MESSAGES/WindowMaker.mo
usr/share/locale/ca/LC_MESSAGES/WINGs.mo
usr/share/locale/pl/LC_MESSAGES/WindowMaker.mo
usr/share/locale/et/LC_MESSAGES/WPrefs.mo
usr/share/locale/et/LC_MESSAGES/WindowMaker.mo
usr/share/locale/ms/LC_MESSAGES/WindowMaker.mo
usr/share/locale/bs/LC_MESSAGES/WindowMaker.mo
usr/share/WindowMaker/menu.pt
usr/share/WindowMaker/plmenu.ko
usr/share/WindowMaker/menu.sk
usr/share/WindowMaker/plmenu.de
usr/share/WindowMaker/plmenu.bg
usr/share/WindowMaker/plmenu.pl
usr/share/WindowMaker/menu.ru
usr/share/WindowMaker/Icons/*.png
usr/share/WindowMaker/Icons/*.tiff
usr/share/WindowMaker/Icons/*.xpm
usr/share/WindowMaker/Icons/README
usr/share/WindowMaker/plmenu
usr/share/WindowMaker/menu.es
usr/share/WindowMaker/wmmacros
usr/share/WindowMaker/menu.hu
usr/share/WindowMaker/menu.he
usr/share/WindowMaker/menu.sl
usr/share/WindowMaker/menu
usr/share/WindowMaker/Backgrounds/BlueImage.jpeg
usr/share/WindowMaker/menu.nl
usr/share/WindowMaker/plmenu.ja
usr/share/WindowMaker/Styles/*.style
usr/share/WindowMaker/menu.ro
usr/share/WindowMaker/menu.bg
usr/share/WindowMaker/menu.se
usr/share/WindowMaker/background.menu
usr/share/WindowMaker/menu.ca
usr/share/WindowMaker/menu.hr
usr/share/WindowMaker/menu.fr
usr/share/WindowMaker/menu.cz
usr/share/WindowMaker/menu.da
usr/share/WindowMaker/menu.ko
usr/share/WindowMaker/plmenu.sk
usr/share/WindowMaker/plmenu.fi
usr/share/WindowMaker/plmenu.it
usr/share/WindowMaker/menu.ja
usr/share/WindowMaker/menu.fi
usr/share/WindowMaker/Themes/*.style
usr/share/WindowMaker/plmenu.da
usr/share/WindowMaker/plmenu.ro
usr/share/WindowMaker/README.themes
usr/share/WindowMaker/menu.de
usr/share/WindowMaker/plmenu.es
usr/share/WindowMaker/README
usr/share/WindowMaker/plmenu.fr
usr/share/WindowMaker/menu.no
usr/share/WindowMaker/menu.it
usr/share/WindowMaker/plmenu.hr
usr/share/WindowMaker/IconSets/Default.iconset
usr/share/WindowMaker/menu.pl
usr/share/WindowMaker/menu.el
usr/share/WindowMaker/menu.zh_TW
usr/share/WindowMaker/plmenu.zh_CN
usr/share/WindowMaker/plmenu.zh_TW
usr/share/WindowMaker/menu.gl
usr/share/WindowMaker/menu.tr
usr/share/WindowMaker/menu.zh_CN
usr/share/WindowMaker/Pixmaps/*.xpm
usr/share/WindowMaker/Pixmaps/*.png
usr/share/WINGs/defaultIcon.xpm
usr/share/WINGs/defaultIcon.tiff
usr/share/WINGs/Images.xpm
usr/share/WINGs/Images.tiff
usr/share/lib/GNUstep/System/Applications/WPrefs.app/WPrefs.xpm
usr/share/lib/GNUstep/System/Applications/WPrefs.app/WPrefs.tiff
usr/share/lib/GNUstep/System/Applications/WPrefs.app/tiff/*.tiff
# Scripts
debian/debianfiles/wmaker			usr/bin
debian/debianfiles/upgrade-windowmaker-defaults usr/sbin
# Theme
debian/debianfiles/Theme/Debian			usr/share/WindowMaker/Themes
debian/debianfiles/Theme/debian.tiff		usr/share/WindowMaker/Backgrounds
# Configuration
etc/WindowMaker/WMGLOBAL			etc/GNUstep/Defaults
etc/WindowMaker/WMState				etc/GNUstep/Defaults
debian/debianfiles/conf/WMWindowAttributes	etc/GNUstep/Defaults
debian/debianfiles/conf/WMRootMenu		etc/GNUstep/Defaults
debian/debianfiles/conf/WindowMaker		etc/GNUstep/Defaults
debian/debianfiles/wmaker-common.desktop	usr/share/xsessions
# Menu
debian/debianfiles/menu/wmappearance		etc/menu-methods
# READMES, from the temporal path (see README section in debian/rules)
README.po					usr/share/doc/wmaker
README.definable-cursor				usr/share/doc/wmaker
README.WPrefs					usr/share/doc/wmaker
README.WPrefs.po				usr/share/doc/wmaker
