#!/bin/sh
set -e

case "$1" in
  remove)
    if [ -x /usr/bin/update-menus ] ; then
      update-menus
    fi
  ;;
  purge|upgrade|abort-install|disappear)
    # nothing to do
  ;;
  failed-upgrade)
    # this is an upgrade, and it has failed. What can fail?
    exit 1
  ;;
  abort-upgrade)
    # preinst failed, leave things like they were
  ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
