#
# GNUmakefile for NextSpace frameworks
#
include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = nextspace-frameworks
VERSION = 0.95
SUBPROJECTS = \
    SystemKit \
    DesktopKit \
    SoundKit

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble

