#
# GNUmakefile for CUBE frameworks
#
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
    NXFoundation \
    NXSystem \
    NXAppKit \

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble

