#!/bin/sh

#
# Creates a Makefile.am file containing all the stuff to install 
# wmaker data
#




DIRS="Backgrounds Defaults IconSets Icons Pixmaps Styles Themes"

FILE=Makefile.am

spit() {
	echo -n "$*" >> $FILE
}

spitln() {
	echo "$*" >> $FILE
}



rm -f $FILE




spitln SUBDIRS = $DIRS
spitln
spitln prefsdatadir = '$(pkgdatadir)'
spitln


EXCEPT="Makefile.am Makefile.in Makefile mkMakefile $FILE"

spit prefsdata_DATA =

FILES=`ls -1|grep -v \~`
FILES=`echo $FILES`

for f in $FILES; do
	ok=1
	for i in $EXCEPT; do
		if test "$i" = "$f"; then
			ok=0	
			break
		fi
	done	
	if [ -f $f -a $ok = 1 ]; then
		spitln \\
		spit "	$f"
	fi
done


spitln
spitln

spitln EXTRA_DIST = '$(prefsdata_DATA)' mkMakefile
spitln
spitln
