#!/bin/sh

# [Christophe CURIS, 2015/01/31]
# This script is now reporting itself as deprecated (this should have been done
# a long time ago), so it should be kept for at least 2 years from now in order
# to allow users to update their scripts, and then removed.

if test $# -eq 0; then
      echo "Error: $0 is deprecated, please use 'pkg-config wrlib ...'" >&2
      exit 1
fi

while test $# -gt 0; do
  case $1 in
    --cflags)
        echo "Warning: $0 is deprecated, please use 'pkg-config wrlib --cflags'" >&2
	pkg-config wrlib --cflags
        ;;
    --ldflags|--lflags)
	echo "Warning: $0 is deprecated, please use 'pkg-config wrlib --libs'" >&2
        pkg-config wrlib --libs-only-L
        ;;
    --libs)
	echo "Warning: $0 is deprecated, please use 'pkg-config wrlib --libs'" >&2
        pkg-config wrlib --libs
        ;;
    *)
	echo "Error: $0 is deprecated, please use 'pkg-config wrlib ...'" >&2
	exit 1
	;;
  esac
  shift
done
