include $(GNUSTEP_MAKEFILES)/common.make
include ../../Version

TEST_TOOL_NAME = load_backends
load_backends_OBJC_FILES = load_backends.m

ADDITIONAL_CPPFLAGS := -DVER=\"$(INTERFACE_VERSION_NUMBER)\"

include $(GNUSTEP_MAKEFILES)/test-tool.make
