# -*- mode: makefile-gmake -*-

ADDITIONAL_OBJCFLAGS += -DWITH_UPOWER
ADDITIONAL_INCLUDE_DIRS += -I../.. `pkg-config --cflags dbus-1 upower-glib`
ADDITIONAL_LDFLAGS += `pkg-config --libs dbus-1 upower-glib`
ADDITIONAL_GUI_LIBS += -lDesktopKit -lSystemKit
