#
# GNUmakefile.preamble
#

# Additional flags to pass to the preprocessor
ADDITIONAL_CPPFLAGS += 

# Additional flags to pass to Objective C compiler
ADDITIONAL_OBJCFLAGS += 

# Additional flags to pass to C compiler
ADDITIONAL_CFLAGS += 

# Additional flags to pass to the linker
ADDITIONAL_LDFLAGS += -lNXFoundation

# Additional include directories the compiler should search
ADDITIONAL_INCLUDE_DIRS +=

# Additional library directories the linker should search
ADDITIONAL_LIB_DIRS +=

