/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import <AppKit/AppKit.h>

int main(int argc, const char *argv[]) 
{
  return NSApplicationMain(argc, argv);
}
