#
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
Login \
Workspace \
Preferences \
Terminal \
TextEdit-4 \
TimeMon \
Review \
OpenUp

###WindowMaker \

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble

