#
# GNUmakefile.preamble
#

ADDITIONAL_OBJCFLAGS += -W -Wall -Wno-import -Wno-unused -Wno-unused-parameter -O2 -pipe
ADDITIONAL_CFLAGS += -W -Wall
ADDITIONAL_LDFLAGS += -lSystemKit -lDesktopKit -lSoundKit -lgnustep-base -lgnustep-gui