#
# GNUmakefile.preamble
#

ifeq ($(findstring gnu, $(GNUSTEP_TARGET_OS)), gnu)
  ADDITIONAL_OBJCFLAGS += -DLinux
  ADDITIONAL_CFLAGS += -DLinux
endif

ADDITIONAL_OBJCFLAGS += -W -Wall -Wno-import -Wno-unused -Wno-unused-parameter -O2 -pipe
ADDITIONAL_CFLAGS += -W -Wall
ADDITIONAL_LDFLAGS += -lSystemKit -lDesktopKit -l gnustep-base -lgnustep-gui