
after-clean::
#	rm -rf Documentation

after-distclean::
#	rm -fr Documentation

after-install::
	ln -s $(DESTDIR)/usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Images /usr/NextSpace/Images
	ln -s $(DESTDIR)/usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Fonts /Library/Fonts

after-uninstall::
	rm -r $(DESTDIR)/usr/NextSpace/Images
	rm -r $(DESTDIR)/Library/Fonts
