ifndef CMAKE
  CMAKE=cmake
endif
ifndef CC
  CC=clang
endif

before-all::
	@ if [ ! -e .build ];then \
		mkdir .build;\
	  fi
	@ cd .build; ${CMAKE} .. -DCMAKE_C_COMPILER=${CC}

after-clean::
	@ rm -rf .build
	# @ rm -rf cmake/CMakeFiles
	# @ rm -f cmake/CMakeCache.txt
	# @ rm -f cmake/Makefile
	# @ rm -f cmake/cmake_install.cmake
	@ rm -f config.h
	@ rm -f GNUmakefile.config
