# -*- mode: makefile-gmake -*-

ADDITIONAL_INCLUDE_DIRS += -I../SystemKit/derived_src

ADDITIONAL_OBJCFLAGS += -Wno-import -Wno-unused -pipe -Wno-format-security

ADDITIONAL_LDFLAGS += -L../SystemKit/SystemKit.framework -lSystemKit -lmagic
