.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH wxpaste 1 "March 1998"
.SH "НАИМЕНОВАНИЕ"
wxpaste \- выводит содержимое буфера на стандартный вывод.
.SH "СИНТАКСИС"
.B wxpaste
[опции]
.SH "ОПИСАНИЕ"
.B wxpaste
выводит содержимое указанного буфера на стандартный вывод. Если буфер не указан,
то по умолчанию будет использоваться буфер 0.
.PP
.SH "ОПЦИИ"
.TP
.B \-cutbuffer номер
Данные будут браться из указанного буфера заместо умолчального буфера 0.
.TP
.B \-display имя\-дисплея
Указывает дисплей откуда wxpaste будет брать данные.
.TP
.B \-selection [имя]
Данные будут скопированы из именованого выбора. Если выборка из именованого
выделения не удаётся, то используется буфер по умолчанию. Умолчальное
значение именованого выбора \- PRIMARY.
.PP
.SH "ОШИБКИ"
.TP
Опция \-selection должна быть последней. Синтаксис мог бы быть и лучше, но
обратная совместимость не позволяет этого сделать…

Типы выбора INCR и MULTIPLE не поддерживаются. На самом деле поддерживаются
только простые текстовые выделения, которых должно быть достаточно для
большинства случаев использования этой утилиты.
.SH "СМОТРИ ТАКЖЕ"
.BR wxcopy (1),
.BR wmaker (1)
.SH "АВТОРЫ"
Window Maker написан Alfredo K. Kojima <kojima@windowmaker.info>,
Dan Pascu <dan@windowmaker.org> и дополнен вкладом многих людей по всему
интернету.
.PP
Это руководство было написано Marcelo E. Magallon, <mmagallo@debian.org>.
Перевод на русский язык осуществил NIR aka Ginko <faust@gmx.com>.
