.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH seticons 1 "March 1998"
.SH NAME
seticons \- sets the icon images used in Window Maker
.SH SYNOPSIS
.B seticons
.I iconsfile
.SH DESCRIPTION
.B seticons
reads
.I iconsfile
and writes its contents to the
.I WMWindowAttributes
domain, effectively
setting the icons Window Maker uses for a given class (for example,
XTerm, "xterm.XTerm", "rxvt.XTerm", "pine.XTerm", etc)
.SH OPTIONS
.TP
.B \-\-help
print a help message with the list of options
.TP
.B \-\-version
print the version of Window Maker from which the program comes
.SH ENVIRONMENT
.IP GNUSTEP_USER_ROOT
specifies the initial path for the Defaults directory. "Defaults/" is
appended to this variable to determine the actual location of the
databases. If the variable is not set, it defaults to "~/GNUstep"
.SH FILES
.IP GNUSTEP_USER_ROOT/Defaults/WMWindowAttributes
This is the actual file that's written.
.SH SEE ALSO
.BR geticonset (1),
.BR wmaker (1)
.SH AUTHOR
This man page was written by Marcelo Magallon <mmagallo@debian.org>.
.PP
Window Maker was written by Alfredo K. Kojima <kojima@windowmaker.info>.
