.TH "Window Maker" 8 "March 2001" "Debian Project"
.SH NAME
upgrade-windowmaker-defaults \- Convert old wmaker configuration files
.SH SYNOPSIS
.B upgrade-windowmaker-defaults
.SH DESCRIPTION
Some old versions of Window Maker used different names or different syntax
for some configuration options, which in turn used to cause some newer
versions of Window Maker not to start up correctly.  Nowadays this is no
longer a problem but this utility is provided to support upgrades from these
old versions of Window Maker.
.SH SEE ALSO
The Window Maker User Guide
.PP
The Window Maker FAQ
.PP
The Window Maker changelog and NEWS files (in /usr/share/doc/wmaker)
.PP
.BR wmaker (1)
.SH AUTHOR
This utility and manpage were written by Marcelo E. Magallon,
<mmagallo@debian.org>, for the Debian Project.  It might be used freely by
others.
