.TH wmiv "1" "June 2015"
.SH NAME
wmiv \- quick image viewer using wrlib
.SH SYNOPSIS
.B wmiv
.RI [ \,image(s)\/ | \,directory\/ ]
.SH OPTIONS
.TP
.B \-\-help
print help text
.TP
.B \-\-version
print version
.SH KEYS
.TP
[+]
zoom in
.TP
[\-]
zoom out
.TP
[Esc]
actual size
.TP
[D]
launch diaporama mode
.TP
[L]
rotate image on the left
.TP
[Q]
quit
.TP
[R]
rotate image on the right
.TP
[▸]
next image
.TP
[◂]
previous image
.TP
[▴]
first image
.TP
[▾]
last image
.SH AUTHOR
.B wmiv
is a part of Window Maker.  It was written by David Maciejak.
