#
# GNUmakefile for NextSpace frameworks
#
include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = nextspace-os_files
VERSION = 0.95

RESOURCE_SET_NAME = nextspace-os_files
$(RESOURCE_SET_NAME)_RESOURCE_FILES = etc usr root dot_hidden

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/resource-set.make
-include GNUmakefile.postamble

