.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH wmsetbg 1 "Leden 1999"
.SH JMÉNO
wmsetbg \- nastaví pozadí hlavního okna v X11
.SH SYNTAXE
.B wmsetbg
[\-display] [\-\-version] [\-\-help] [{\-b|\-\-back\-color} \fIbarva\fP]
[{\-t|\-\-tile}|{\-e|\-\-center}|{\-s|\-\-scale}|{\-a|\-\-maxscale} \fIobrázek\fP]
[{\-d|\-\-dither}|{\-m|\-\-match}] [\-u|\-\-update\-wmaker]
[{\-D|\-\-update\-domain} \fIdoména\fP] [{\-c|\-\-colors} \fIcpc\fP]
[{\-p|\-\-parse} \fItextura\fP] [{\-w|\-\-workspace} \fIpracovní plocha\fP]
.SH POPIS
.B wmsetbg
naèítá daný
.I obrázek
(XPM, PNG, jpeg, Tiff, raw PPM) a vlo¾í ho do hlavního okna. Obrázek je mo¾né
zvìt¹it, nebo ho opakovat aby vyplnil hlavní okno. Window Maker pou¾íva
tento pøíkaz internì na nastavení pozadí pøi startu.
.SH VOLBY
.TP
.B \-a|\-\-maxscale
zvìt¹í daný \fIobrázek\fP pøi dodr¾ení pomìru stran
.TP
.B \-e|\-\-center
vlo¾í \fIobrázek\fP do støedu okna
.TP
.B \-t|\-\-tile
vytvoøí z \fIobrázku\fP dla¾dice
.TP
.B \-s|\-\-scale
roztáhne daný \fIobrázek\fP (standartnì)
.TP
.B \-d|\-\-dither
rezervuje barvy
.TP
.B \-m|\-\-match
shodné barvy
.TP
.B \-u|\-\-update\-wmaker
zapí¹e zmìnu do databáze nastavení Window Makera
.TP
.B \-D|\-\-update\-domain
zapí¹e zmìnu do databáze \fIdomény\fP
.TP
.B \-c|\-\-colors
pou¾íje urèitý poèet barev na kanál
.TP
.B \-p|\-\-parse
parsuje danou \fItexturu\fP jako \fIproplist stylu textur\fP
.TP
.B \-w|\-\-workspace
nastaví pozadí jen na dané \fIpracovní plo¹e\fP
.TP
.B \-\-help
vypí¹e nápovìdu
.TP
.B \-\-version
vypí¹e èíslo verze
.SH PODÍVEJTE SE TAKÉ
.BR wmaker (1)
.SH AUTOR
Autorem Window Makera je Alfredo K. Kojima <kojima@windowmaker.info>.
wmsetbg napsal Dan Pascu <dan@windowmaker.info>
.PP
Tuto manuálovou stránku napsal Marcelo Magallon <mmagallo@debian.org>.
.PP
Do èe¹tiny pøelo¾il Jiøí Hnídek <jiri.hnidek@vslib.cz>.
