# Automatically generated by ./configure -- do not edit
BINDIR=/usr/NextSpace/bin
SBINDIR=/usr/NextSpace/sbin
DATAROOTDIR=/usr/NextSpace/share
LIBDIR=/usr/NextSpace/lib
INCLUDEDIR=/usr/NextSpace/include
MANDIR=/usr/NextSpace/Documentation/man
DOCDIR=/usr/NextSpace/Documentation/doc
CC=cc
AR=ar
RANLIB=-ranlib
MAKE=make
